### ISSUE TITLE
Log4j 2 Configuration

### ISSUE THREAD

**Issue by Florian-Pubert** [lgdd/liferay-healthcheck#9]
On liferay 7.4ux the log4j configuration need to be :

```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN" xmlns="http://logging.apache.org/log4j/2.0/config">
  <Loggers>
    <Logger name="com.github.lgdd.liferay.health" level="warn"/>
  </Loggers>
</Configuration>
```

If not we have this log error on startup : ERROR [Start Level: Equinox Container: 3e07db71-2e7b-44ed-a493-0620a4746893][Log4jConfigUtil:62] Log4J 2 <Configuration> is required

**Comment by lgdd** [comment]
@Florian-Pubert @ghenadiibatalski Sorry for the late response and thank you both for reporting and fixing this issue 🙏
